### ISSUE TITLE
Help (again)

### ISSUE THREAD

**Issue by Lbruu** [DasJNNJ/Muck-Cheat-Injector#1]
![Screenshot 2021-06-10 100932](https://user-images.githubusercontent.com/85609810/121550038-fcb5fe00-c9d3-11eb-825a-8fa92a66a8f7.png)

This is what i see when i download the injector. idk if theres supposed to be an exe

**Comment by DasJNNJ** [comment]
Download from the [releases page](https://github.com/DasJNNJ/Muck-Cheat-Injector/releases/latest/)
